version: '{build}'
environment:
  matrix:    
    - node_version: '10'    
install:
  - ps: Install-Product node $env:node_version x64
  - ps: ./install-sdk.ps1
  
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
services:
  - mssql2016
  - postgresql101
  - mongodb
  - mysql
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\artifacts\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://www.myget.org/F/xabaril/api/v2/package
  api_key:
    secure: uESSL/tmtvlykkG7fgS0dFd4UpR+12vOSqFN3AiuHhxJpDiUl6EWZbgNoxcrRrch
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: w87T+lmkPt0ZgcWBkTsJwQX0VFSZc4Jb9vMLehno59sDyFOA8FaEBJlGH13gWCjD
  skip_symbols: true
  on:
    appveyor_repo_tag: true