apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: healthchecks-admin
rules:
  - apiGroups:
      - "" #core API group
    resources:
      - services
      - pods
      - deployments
      - secrets
      - configmaps
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - "aspnetcore.ui"
    resources:
      - "*"
    verbs:
      - "*"
