apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: healthchecks-admin
subjects:
  - kind: ServiceAccount
    name: healthchecks-admin
    namespace: healthchecks
roleRef:
  kind: ClusterRole
  name: healthchecks-admin
  apiGroup: rbac.authorization.k8s.io
