apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: healthchecks-ui-k8s-operator-deploy
  namespace: lande
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: healthchecks-ui-k8s-operator
    spec:
      containers:
        - name: healthchecks-ui-k8s-operator
          image: healthchecksui-k8s-operator
          imagePullPolicy: Never
