name: HealthChecks CosmosDb CD

on:
  push:
    tags:
      - release-cosmosdb-*  # Push events to release-cosmosdb*

jobs:
  build:
    env:
      BUILD_CONFIG: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.CosmosDb/HealthChecks.CosmosDb.csproj
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.CosmosDb/HealthChecks.CosmosDb.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.CosmosDb.Tests/HealthChecks.CosmosDb.Tests.csproj --verbosity normal
    - name: dotnet pack
      run: dotnet pack ./src/HealthChecks.CosmosDb/HealthChecks.CosmosDb.csproj -c $BUILD_CONFIG --include-source --include-symbols -o ./artifacts
    - name: setup nuget
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        nuget-version: latest
    - name: Publish CosmosDb Health Check nuget
      run: dotnet nuget push ./artifacts/AspNetCore.HealthChecks.CosmosDb.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
