name: HealthChecks OpenIdConnectServer CI

on:
  push:
    #branches: [ master ]
    paths:
      - src/HealthChecks.OpenIdConnectServer/**
      - test/HealthChecks.IdSvr.Tests/**
      - .github/workflows/healthchecks_idsvr_ci.yml
    tags-ignore:
      - preview-*
  pull_request:
    #branches: [ master ]
    paths:
    - src/HealthChecks.OpenIdConnectServer/**
    - test/HealthChecks.IdSvr.Tests/**
    - .github/workflows/healthchecks_idsvr_ci.yml

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      idsvr:
        image: nakah/identityserver4
        ports:
          - 8888:80
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.OpenIdConnectServer/HealthChecks.OpenIdConnectServer.csproj
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.OpenIdConnectServer/HealthChecks.OpenIdConnectServer.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.OpenIdConnectServer.Tests/HealthChecks.OpenIdConnectServer.Tests.csproj --verbosity normal
