name: HealthChecks KAFKA CI

on:
  push:
    #branches: [ master ]
    paths:
      - src/HealthChecks.Kafka/**
      - test/HealthChecks.Kafka.Tests/**
      - .github/workflows/healthchecks_kafka_ci.yml
    tags-ignore:
      - preview-*
  pull_request:
    #branches: [ master ]
    paths:
    - src/HealthChecks.Kafka/**
    - test/HealthChecks.Kafka.Tests/**
    - .github/workflows/healthchecks_kafka_ci.yml

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      kafka:
        image: confluent/kafka
        ports:
          - 9092:9092
        env: 
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_PORT: 9092
      zookeeper:
        image: confluent/zookeeper
        ports:
          - 2181:2181
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.Kafka/HealthChecks.Kafka.csproj
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.Kafka/HealthChecks.Kafka.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.Kafka.Tests/HealthChecks.Kafka.Tests.csproj --verbosity normal
