name: HealthChecks SolR CI

on:
  push:
    #branches: [ master ]
    paths:
    - src/HealthChecks.SolR/**
    - test/HealthChecks.SolR.Tests/**
    - .github/workflows/healthchecks_solr_ci.yml
  pull_request:
    #branches: [ master ]
    paths:
    - src/HealthChecks.SolR/**
    - test/HealthChecks.SolR.Tests/**
    - .github/workflows/healthchecks_solr_ci.yml

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      consul:
        image: solr:8.4.1
        ports:
          - 8983:8983
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.SolR/HealthChecks.SolR.csproj
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.SolR/HealthChecks.SolR.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.SolR.Tests/HealthChecks.SolR.Tests.csproj --verbosity normal
