name: HealthChecks RavenDb CI

on:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.RavenDB/**
      - test/HealthChecks.RavenDb.Tests/**
      - .github/workflows/healthchecks_ravendb_ci.yml
    tags-ignore:
      - preview-*
  pull_request:
    branches: [ master ]
    paths:
    - src/HealthChecks.RavenDB/**
    - test/HealthChecks.RavenDb.Tests/**
    - .github/workflows/healthchecks_ravendb_ci.yml

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      ravendb:
        image: ravendb/ravendb
        ports:
          - 9030:8080
        env: 
          RAVEN_ARGS: --Setup.Mode=None
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.RavenDB/HealthChecks.RavenDB.csproj
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.RavenDB/HealthChecks.RavenDB.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.RavenDb.Tests/HealthChecks.RavenDb.Tests.csproj --verbosity normal
