name: HealthChecks AzureStorage DB CI

on:
  push:
   branches: [ master ]
   paths:
    - src/HealthChecks.AzureStorage/**
    - test/HealthChecks.AzureStorage.Tests/**
    - .github/workflows/healthchecks_azurestorage_ci.yml
   tags-ignore:
    - release-*
    
  pull_request:
    branches: [ master ]
    paths:
    - src/HealthChecks.AzureStorage/**
    - test/HealthChecks.AzureStorage.Tests/**
    - .github/workflows/healthchecks_azurestorage_ci.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.AzureStorage/HealthChecks.AzureStorage.csproj
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.AzureStorage/HealthChecks.AzureStorage.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.AzureStorage.Tests/HealthChecks.AzureStorage.Tests.csproj --verbosity normal
