name: HealthChecks SendGrid CI

on:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.SendGrid/**
      - test/HealthChecks.SendGrid.Tests/**
      - .github/workflows/healthchecks_sendgrid_ci.yml
    tags-ignore:
      - release-*
  pull_request:
    branches: [ master ]
    paths:
    - src/HealthChecks.SendGrid/**
    - test/HealthChecks.SendGrid.Tests/**
    - .github/workflows/healthchecks_sendgrid_ci.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.SendGrid/HealthChecks.SendGrid.csproj
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.SendGrid/HealthChecks.SendGrid.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.SendGrid.Tests/HealthChecks.SendGrid.Tests.csproj --verbosity normal
