name: HealthChecks Azure Table Storage Preview CD

on:
  push:
    tags:
      - preview-azuretablestorage-*
      - preview-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_preview_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      VERSION_SUFFIX_PREFIX: rc1
      PROJECT_PATH: ./src/HealthChecks.Azure.Data.Tables/HealthChecks.Azure.Data.Tables.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Azure.Data.Tables