name: HealthChecks Redis CI

on:
  push:
    #branches: [ master ]
    paths:
    - src/HealthChecks.Redis/**
    - test/HealthChecks.Redis.Tests/**
    - .github/workflows/healthchecks_redis_ci.yml
  pull_request:
    #branches: [ master ]
    paths:
    - src/HealthChecks.Redis/**
    - test/HealthChecks.Redis.Tests/**
    - .github/workflows/healthchecks_redis_ci.yml

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      sqlserver:
        image: redis:alpine
        ports:
          - 6379:6379
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.Redis/HealthChecks.Redis.csproj
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.Redis/HealthChecks.Redis.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.Redis.Tests/HealthChecks.Redis.Tests.csproj --verbosity normal
