name: HealthChecks Publisher.CloudWatch CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.Publisher.CloudWatch/**
      - test/HealthChecks.Publisher.CloudWatch.Tests/**
      - .github/workflows/healthchecks_publisher_cloudwatch_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.Publisher.CloudWatch/**
      - test/HealthChecks.Publisher.CloudWatch.Tests/**
      - .github/workflows/healthchecks_publisher_cloudwatch_ci.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    env:
      AWS_REGION: us-east-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
      - name: Restore
        run: |
          dotnet restore ./src/HealthChecks.Publisher.CloudWatch/HealthChecks.Publisher.CloudWatch.csproj &&
          dotnet restore ./test/HealthChecks.Publisher.CloudWatch.Tests/HealthChecks.Publisher.CloudWatch.Tests.csproj
      - name: Check formatting
        run: |
          dotnet format --no-restore --verify-no-changes --severity warn ./src/HealthChecks.Publisher.CloudWatch/HealthChecks.Publisher.CloudWatch.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1) &&
          dotnet format --no-restore --verify-no-changes --severity warn ./test/HealthChecks.Publisher.CloudWatch.Tests/HealthChecks.Publisher.CloudWatch.Tests.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1)
      - name: Build
        run: |
          dotnet build --no-restore ./src/HealthChecks.Publisher.CloudWatch/HealthChecks.Publisher.CloudWatch.csproj &&
          dotnet build --no-restore ./test/HealthChecks.Publisher.CloudWatch.Tests/HealthChecks.Publisher.CloudWatch.Tests.csproj
      - name: Test
        run: dotnet test --no-restore --no-build ./test/HealthChecks.Publisher.CloudWatch.Tests/HealthChecks.Publisher.CloudWatch.Tests.csproj
