name: HealthChecks Azure Blob Storage Preview CD

on:
  push:
    tags:
      - preview-azureblobstorage-*
      - preview-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_preview_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      VERSION_SUFFIX_PREFIX: rc1
      PROJECT_PATH: ./src/HealthChecks.Azure.Storage.Blobs/HealthChecks.Azure.Storage.Blobs.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Azure.Storage.Blobs