name: HealthChecks MongoDb Preview CD

on:
  push:
    tags:
      - preview-mongodb-*

jobs:
  build:
    env:
      BUILD_CONFIG: Release
      VERSION_SUFFIX: -rc2.${{ github.run_number }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.MongoDb/HealthChecks.MongoDb.csproj
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.MongoDb/HealthChecks.MongoDb.csproj
    - name: Pack
      run: dotnet pack --no-restore ./src/HealthChecks.MongoDb/HealthChecks.MongoDb.csproj --version-suffix $VERSION_SUFFIX -c $BUILD_CONFIG --include-source --include-symbols -o ./artifacts
    - name: setup nuget
      uses: NuGet/setup-nuget@v1.0.5
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        nuget-version: latest
    - name: Publish MongoDb Health Check nuget
      run: dotnet nuget push ./artifacts/AspNetCore.HealthChecks.MongoDb.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
