name: HealthChecks CosmosDb Preview CD

on:
  push:
    tags:
      - preview-cosmosdb-*
      - preview-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_preview_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      VERSION_SUFFIX_PREFIX: rc2
      PROJECT_PATH: ./src/HealthChecks.CosmosDb/HealthChecks.CosmosDb.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.CosmosDb