name: HealthChecks Consul Preview CD

on:
  push:
    tags:       
      - preview-consul-*  # Push events to release-arangodb* 
jobs:
  build:
    env:
      BUILD_CONFIG: Release
      VERSION_SUFFIX: -rc2.${{ github.run_number }}
    runs-on: ubuntu-latest
    services:
      consul:
        image: consul:latest
        ports:
          - 8500:8500
          - 8600:8600
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.Consul/HealthChecks.Consul.csproj
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.Consul/HealthChecks.Consul.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.Consul.Tests/HealthChecks.Consul.Tests.csproj --verbosity normal
    - name: dotnet pack 
      run: dotnet pack ./src/HealthChecks.Consul/HealthChecks.Consul.csproj --version-suffix $VERSION_SUFFIX -c $BUILD_CONFIG --include-source --include-symbols -o ./artifacts
    - name: setup nuget
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        nuget-version: latest
    - name: Publish Consul Health Check nuget
      run: dotnet nuget push ./artifacts/AspNetCore.HealthChecks.Consul.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
