name: HealthChecks OpenIdConnectServer CD

on:
  push:
    tags:       
      - release-openidconnectserver-*

jobs:
  build:
    env:
      BUILD_CONFIG: Release
    runs-on: ubuntu-latest
    services:
      idsvr:
        image: nakah/identityserver4
        ports:
          - 8888:80
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.OpenIdConnectServer/HealthChecks.OpenIdConnectServer.csproj
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.IdSvr/HealthChecks.OpenIdConnectServer.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.OpenIdConnectServer.Tests/HealthChecks.OpenIdConnectServer.Tests.csproj --verbosity normal
    - name: dotnet pack 
      run: dotnet pack ./src/HealthChecks.OpenIdConnectServer/HealthChecks.OpenIdConnectServer.csproj -c $BUILD_CONFIG --include-source --include-symbols -o ./artifacts
    - name: setup nuget
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        nuget-version: latest
    - name: Publish IdSvr Health Check nuget
      run: dotnet nuget push ./artifacts/AspNetCore.HealthChecks.OpenIdConnectServer.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
