name: HealthChecks IbmMQ CI

on:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.IbmMQ/**
      - test/HealthChecks.IbmMQ.Tests/**
      - .github/workflows/healthchecks_ibmmq_ci.yml
    tags-ignore:
      - preview-*
  pull_request:
    branches: [ master ]
    paths:
    - src/HealthChecks.IbmMQ/**
    - test/HealthChecks.IbmMQ.Tests/**
    - .github/workflows/healthchecks_ibmmq_ci.yml

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      consul:
        image: ibmcom/mq
        ports:
          - 1414:1414
          - 9157:9157
        env:
          LICENSE: accept
          MQ_QMGR_NAME: QM1
          MQ_APP_PASSWORD: 12345678
          MQ_ENABLE_METRICS: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.IbmMQ/HealthChecks.IbmMQ.csproj
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.IbmMQ/HealthChecks.IbmMQ.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.IbmMQ.Tests/HealthChecks.IbmMQ.Tests.csproj --verbosity normal
