name: HealthChecks Aws.S3 CI

on:
  push:
   #branches: [ master ]
   paths:
    - src/HealthChecks.Aws.S3/**
    - test/HealthChecks.Aws.S3.Tests/**
    - .github/workflows/healthchecks_aws_s3_ci.yml
   #tags-ignore:
   # - preview-*
    
  pull_request:
    #branches: [ master ]
    paths:
    - src/HealthChecks.Aws.S3/**
    - test/HealthChecks.Aws.S3.Tests/**
    - .github/workflows/healthchecks_aws_s3_ci.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.Aws.S3/HealthChecks.Aws.S3.csproj
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.Aws.S3/HealthChecks.Aws.S3.csproj
