name: HealthChecks DynamoDb CI

on:
  push:
    #branches: [ master ]
    paths:
      - src/HealthChecks.DynamoDb/**
      - test/HealthChecks.DynamoDb.Tests/**
      - .github/workflows/healthchecks_dynamodb_ci.yml
    tags-ignore:
      - preview-*
  pull_request:
    #branches: [ master ]
    paths:
    - src/HealthChecks.DynamoDb/**
    - test/HealthChecks.DynamoDb.Tests/**
    - .github/workflows/healthchecks_dynamodb_ci.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.DynamoDb/HealthChecks.DynamoDb.csproj
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.DynamoDb/HealthChecks.DynamoDb.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.DynamoDb.Tests/HealthChecks.DynamoDb.Tests.csproj --verbosity normal
