name: HealthChecks Azure.IoTHub CI

on:
  push:
   #branches: [ master ]
   paths:
    - src/HealthChecks.Azure.IoTHub/**
    - test/HealthChecks.Azure.IoTHub.Tests/**
    - .github/workflows/healthchecks_azure_iothub_ci.yml
   tags-ignore:
    - preview-*
    
  pull_request:
    #branches: [ master ]
    paths:
    - src/HealthChecks.Azure.IoTHub/**
    - test/HealthChecks.Azure.IoTHub.Tests/**
    - .github/workflows/healthchecks_azure_iothub_ci.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.Azure.IoTHub/HealthChecks.Azure.IoTHub.csproj
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.Azure.IoTHub/HealthChecks.Azure.IoTHub.csproj
