name: HealthChecks IbmMQ CI

on:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.IbmMQ/**
      - test/HealthChecks.IbmMQ.Tests/**
      - .github/workflows/healthchecks_ibmmq_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
  pull_request:
    branches: [ master ]
    paths:
    - src/HealthChecks.IbmMQ/**
    - test/HealthChecks.IbmMQ.Tests/**
    - .github/workflows/healthchecks_ibmmq_ci.yml
    - Directory.Build.props
    - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      ibmmq:
        image: ibmcom/mq
        ports:
          - 1414:1414
          - 9157:9157
        env:
          LICENSE: accept
          MQ_QMGR_NAME: QM1
          MQ_APP_PASSWORD: 12345678
          MQ_ENABLE_METRICS: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.IbmMQ/HealthChecks.IbmMQ.csproj
    - name: Check formatting
      working-directory: ./src/HealthChecks.IbmMQ
      run: |
        dotnet tool install -g dotnet-format --version 6.0.243104 --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json
        dotnet format --no-restore --verify-no-changes --severity warn whitespace || (echo "Run 'dotnet format' to fix whitespace issues" && exit 1)
        dotnet format --no-restore --verify-no-changes --severity warn analyzers || (echo "Run 'dotnet format' to fix analyzers issues" && exit 1)
        dotnet format --no-restore --verify-no-changes --severity warn style || (echo "Run 'dotnet format' to fix style issues" && exit 1)
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.IbmMQ/HealthChecks.IbmMQ.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.IbmMQ.Tests/HealthChecks.IbmMQ.Tests.csproj --verbosity normal
