name: HealthChecks Prometheus.Metrics CI

on:
  push:
    #branches: [ master ]
    paths:
      - src/HealthChecks.Prometheus.Metrics/**
      - test/HealthChecks.Prometheus.Metrics.Tests/**
      - .github/workflows/healthchecks_prometheus_metrics_ci.yml
    #tags-ignore:
    #  - preview-*
  pull_request:
    #branches: [ master ]
    paths:
    - src/HealthChecks.Prometheus.Metrics/**
    - test/HealthChecks.Prometheus.Metrics.Tests/**
    - .github/workflows/healthchecks_prometheus_metrics_ci.yml

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      sqlserver:
        image: prometheus_metricsinanutshell/prometheus_metrics-xe-11g
        ports:
          - 1521:1521
          - 5500:5500
        env:
          ORACLE_ALLOW_REMOTE: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.Prometheus.Metrics/HealthChecks.Prometheus.Metrics.csproj
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.Prometheus.Metrics/HealthChecks.Prometheus.Metrics.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.Prometheus.Metrics.Tests/HealthChecks.Prometheus.Metrics.Tests.csproj --verbosity normal
