name: HealthChecks AzureKeyVault DB CD

on:
  push:
    tags:
      - release-azurekeyvault-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.AzureKeyVault/HealthChecks.AzureKeyVault.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.AzureKeyVault
