name: HealthChecks Elastic Search CI

on:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.Elasticsearch/**
      - test/HealthChecks.Elasticsearch.Tests/**
      - .github/workflows/healthchecks_elasticsearch_ci.yml
    tags-ignore:
      - preview-*
  pull_request:
    branches: [ master ]
    paths:
    - src/HealthChecks.Elasticsearch/**
    - test/HealthChecks.Elasticsearch.Tests/**
    - .github/workflows/healthchecks_elasticsearch_ci.yml

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        ports:
          - 9300:9300
          - 9200:9200
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.Elasticsearch/HealthChecks.Elasticsearch.csproj
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.Elasticsearch/HealthChecks.Elasticsearch.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.Elasticsearch.Tests/HealthChecks.Elasticsearch.Tests.csproj --verbosity normal
