name: HealthChecks SQL Server DB CI

on:
  push:
    #branches: [ master ]
    paths:
      - src/HealthChecks.SqlServer/**
      - test/HealthChecks.SqlServer.Tests/**
      - .github/workflows/healthchecks_sqlserver_ci.yml
    tags-ignore:
      - preview-*
  pull_request:
    #branches: [ master ]
    paths:
    - src/HealthChecks.SqlServer/**
    - test/HealthChecks.SqlServer.Tests/**
    - .github/workflows/healthchecks_sqlserver_ci.yml

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server
        ports:
          - 5433:1433
        env: 
          ACCEPT_EULA: Y
          SA_PASSWORD: Password12!
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.SqlServer/HealthChecks.SqlServer.csproj
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.SqlServer/HealthChecks.SqlServer.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.SqlServer.Tests/HealthChecks.SqlServer.Tests.csproj --verbosity normal
