name: HealthChecks NPGSQL DB CI

on:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.NpgSql/**
      - test/HealthChecks.Npgsql.Tests/**
      - .github/workflows/healthchecks_npgsql_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
  pull_request:
    branches: [ master ]
    paths:
    - src/HealthChecks.NpgSql/**
    - test/HealthChecks.Npgsql.Tests/**
    - .github/workflows/healthchecks_npgsql_ci.yml
    - Directory.Build.props
    - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      npgsql:
        image: postgres
        ports:
          - 8010:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Password12!
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.102
        include-prerelease: false
    - name: Restore
      run: |
        dotnet restore ./src/HealthChecks.NpgSql/HealthChecks.NpgSql.csproj &&
        dotnet restore ./test/HealthChecks.Npgsql.Tests/HealthChecks.Npgsql.Tests.csproj
    - name: Check formatting
      run: |
        dotnet format --no-restore --verify-no-changes --severity warn ./src/HealthChecks.NpgSql/HealthChecks.NpgSql.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1) &&
        dotnet format --no-restore --verify-no-changes --severity warn ./test/HealthChecks.Npgsql.Tests/HealthChecks.Npgsql.Tests.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1)
    - name: Build
      run: |
        dotnet build --no-restore ./src/HealthChecks.NpgSql/HealthChecks.NpgSql.csproj &&
        dotnet build --no-restore ./test/HealthChecks.Npgsql.Tests/HealthChecks.Npgsql.Tests.csproj
    - name: Test
      run: dotnet test --no-restore --no-build ./test/HealthChecks.Npgsql.Tests/HealthChecks.Npgsql.Tests.csproj
