name: HealthChecks Redis CD

on:
  push:
    tags:
      - release-redis-*

jobs:
  build:
    env:
      BUILD_CONFIG: Release
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.Redis/HealthChecks.Redis.csproj
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.Redis/HealthChecks.Redis.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.Redis.Tests/HealthChecks.Redis.Tests.csproj --verbosity normal
    - name: dotnet pack
      run: dotnet pack ./src/HealthChecks.Redis/HealthChecks.Redis.csproj -c $BUILD_CONFIG --include-source --include-symbols -o ./artifacts
    - name: setup nuget
      uses: NuGet/setup-nuget@v1.0.5
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        nuget-version: latest
    - name: Publish Redis Health Check nuget
      run: dotnet nuget push ./artifacts/AspNetCore.HealthChecks.Redis.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate


