name: HealthChecks Publisher.Prometheus CI

on:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.Publisher.Prometheus/**
      - test/HealthChecks.Publisher.Prometheus.Tests/**
      - .github/workflows/healthchecks_publisher_prometheus_ci.yml
    tags-ignore:
      - preview-*
  pull_request:
    branches: [ master ]
    paths:
    - src/HealthChecks.Publisher.Prometheus/**
    - test/HealthChecks.Publisher.Prometheus.Tests/**
    - .github/workflows/healthchecks_publisher_prometheus_ci.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.Publisher.Prometheus/HealthChecks.Publisher.Prometheus.csproj
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.Publisher.Prometheus/HealthChecks.Publisher.Prometheus.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.Publisher.Prometheus.Tests/HealthChecks.Publisher.Prometheus.Tests.csproj --verbosity normal
